/**
 * WP-305 — source ontology / projection-boundary contract (V25 S-Tier §8 Lane 3).
 *
 * These tests pin the THREE-SURFACE model (full source packet ⊇ source-review
 * packet ⊋ writer projection) and prove the advisory source lane's input is
 * source-EQUIPPED, closing the source-blind false-positive class (V25-09/10,
 * cleanPass 0.125):
 *   - the assembled source-review input carries the exact source-evidence the
 *     writer projection strips (case allowedUses/forbiddenUses, provenance,
 *     anchor bodies, plan license);
 *   - the writer projection over the SAME packet still strips them (the diet is
 *     not weakened — this ADDS to packet-projection.test.ts, it does not relax it);
 *   - a source-blind (reader-doc-only) or dieted (writer-projection-substituted)
 *     input is REFUSED fail-closed, never silently adjudicated;
 *   - an anchored source_bound case is adjudicable SUPPORTED given the equipped
 *     inputs (the exact class that produced the false invented-detail flags);
 *   - the manifest was tool-regenerated byte-for-byte (18 contracts);
 *   - an ontology change (origin/form/claim-strength on the plan) stales the
 *     source review via the bound source-use-plan hash.
 * ZERO live model calls — the one lane run uses the injected `deps.spawn` seam.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { test } from "./harness.js";
import { fxCase, fxChapter, fxPacket, fxPlan, fxPlanUnit } from "./migrationFixtures.js";
import type { SourcePacketV1 } from "../src/artifacts/artifactTypes.js";
import type { SourceUsePlanV1 } from "../src/contracts/sourceUsePlan.js";
import type { ChapterV21 } from "../src/types.js";
import { sourcePacketHash } from "../src/compiler/sourcePacket.js";
import { writerPacketProjection } from "../src/compiler/sourcePacketProjection.js";
import {
  assembleSourceReviewPacket,
  computeRequiredSourceUnitIds,
  runSourceIntegrityReview,
  type SourceIntegrityLaneInputV1,
  type SourceIntegritySpawnFn,
} from "../src/review/sourceIntegrityReview.js";
import { sourceUsePlanHash } from "../src/contracts/sourceUsePlan.js";
import { sourceReviewIsFresh, type SourceIntegrityReviewV1 } from "../src/contracts/sourceIntegrityReview.js";
import {
  assertSourceReviewPacketEquipped,
  CONTRACT_MANIFEST_PATH,
  computeContractManifest,
  isSourceReviewPacketEquipped,
  loadFrozenManifest,
  SOURCE_PROJECTION_BOUNDARY_CONTRACT,
  SourceProjectionBoundaryError,
  sourceReviewPacketEquippedErrors,
  sourceReviewProjectionIsDistinctFromWriter,
  WRITER_STRIPPED_SOURCE_EVIDENCE,
  writerProjectionLeakedSourceEvidence,
} from "../src/contracts/index.js";

const SCHEMA_SHA = "a".repeat(64);

// ── fixtures: a packet whose named case carries the WRITER-STRIPPED evidence ──

/** A packet whose case really carries allowedUses/forbiddenUses and whose root
 *  carries provenance — the exact fields the writer diet removes and the reviewer
 *  must hold to adjudicate an anchored case SUPPORTED. */
function evidencePacket(): SourcePacketV1 {
  return fxPacket({
    sourceSidecarPath: "state/source-runs/zz-fixture-book/ch01.sidecar.json",
    sourceHash: "b".repeat(64),
    forbiddenClaims: ["no guaranteed outcomes"],
    frameworks: [{ id: "fw1", name: "Framework", members: ["a", "b"], completenessRequired: true }],
    namedCases: [
      fxCase("ch01.ex.a", {
        allowedUses: ["example", "core_move"],
        forbiddenUses: ["do not restamp the named institution onto another case"],
        doNotRestamp: ["ACME Institute"],
      }),
    ],
  });
}

/** A plan FRESH against `packet` whose single unit is the anchored source_bound
 *  case (so it is a REQUIRED source unit — source_bound + ≥1 anchor). */
function freshCasePlan(packet: SourcePacketV1, over: Partial<SourceUsePlanV1> = {}): SourceUsePlanV1 {
  return fxPlan({
    sourcePacketSha256: sourcePacketHash(packet),
    units: [
      fxPlanUnit({
        unitId: "unit.case.ch01.ex.a",
        origin: "source_bound",
        form: "case",
        caseId: "ch01.ex.a",
        anchorIds: ["ch01.ex.a"],
        claimStrength: "descriptive",
        detailSufficiency: "full",
      }),
    ],
    ...over,
  });
}

const NON_V2_SIDECAR = { schemaVersion: "source-v1", namedExamples: [] as unknown[] };

function laneInput(packet: SourcePacketV1, plan: SourceUsePlanV1, chapter: ChapterV21): SourceIntegrityLaneInputV1 {
  return { chapter, plan, packet, sidecar: NON_V2_SIDECAR, anchorCatalog: packet.allowedAnchors, schemaSha256: SCHEMA_SHA };
}

// ── 1. the assembled source-review input is EQUIPPED with the stripped evidence ──

test("equipped: the assembled source-review packet carries the case permissions + provenance the writer strips", () => {
  const packet = evidencePacket();
  const plan = freshCasePlan(packet);
  const reviewPacket = assembleSourceReviewPacket(fxChapter(), plan, packet, NON_V2_SIDECAR, packet.allowedAnchors);

  // Contract-level: equipped (no source-blind/dieted errors).
  assert.deepEqual(sourceReviewPacketEquippedErrors(reviewPacket), []);
  assert.equal(isSourceReviewPacketEquipped(reviewPacket), true);
  assert.doesNotThrow(() => assertSourceReviewPacketEquipped(reviewPacket));

  // Field-level: the exact writer-stripped source-evidence is physically present.
  assert.deepEqual(reviewPacket.sourcePacket.namedCases[0].allowedUses, ["example", "core_move"]);
  assert.deepEqual(reviewPacket.sourcePacket.namedCases[0].forbiddenUses, ["do not restamp the named institution onto another case"]);
  assert.equal(reviewPacket.sourcePacket.sourceSidecarPath, "state/source-runs/zz-fixture-book/ch01.sidecar.json");
  assert.equal(reviewPacket.sourcePacket.sourceHash, "b".repeat(64));
  assert.ok(reviewPacket.sourcePlanLicense.length > 0, "the compiler-owned plan license is present");
  // Anchor BODIES, not bare ids (the reviewer's fuller surface).
  assert.ok(reviewPacket.anchorCatalog.every((a) => typeof a === "object" && typeof a.id === "string" && "text" in a));
});

// ── 2. the writer projection over the SAME packet still strips it (diet intact) ──

test("diet: the writer projection over the same packet strips every writer-stripped source-evidence field", () => {
  const packet = evidencePacket();
  const projection = writerPacketProjection(packet);

  // Precondition: the packet REALLY carries the evidence we claim gets stripped.
  assert.deepEqual(packet.namedCases[0].allowedUses, ["example", "core_move"]);
  assert.ok(packet.namedCases[0].forbiddenUses.length > 0);
  assert.equal(typeof packet.sourceSidecarPath, "string");

  // The diet holds: no writer-stripped source-evidence key leaked (recursive scan).
  assert.deepEqual(writerProjectionLeakedSourceEvidence(projection), []);
  // Spot-check the named ones the task calls out.
  const projected = JSON.parse(JSON.stringify(projection)) as Record<string, unknown>;
  const projectedCase = (projected.namedCases as Array<Record<string, unknown>>)[0];
  assert.ok(!("allowedUses" in projectedCase), "allowedUses must not reach the writer");
  assert.ok(!("forbiddenUses" in projectedCase), "the forbiddenUses rationale must not reach the writer");
  assert.ok(!("sourceSidecarPath" in projected) && !("sourceHash" in projected), "provenance must not reach the writer");
});

// ── 3. distinctness — reviewer packet is a proper superset of the writer diet ──

test("distinctness: the source-review packet is a proper superset of the writer projection (not the dieted view)", () => {
  const packet = evidencePacket();
  const plan = freshCasePlan(packet);
  const reviewPacket = assembleSourceReviewPacket(fxChapter(), plan, packet, NON_V2_SIDECAR, packet.allowedAnchors);
  const projection = writerPacketProjection(packet);
  assert.equal(sourceReviewProjectionIsDistinctFromWriter(reviewPacket, projection), true);
});

// ── 4. source-blind / dieted inputs are REFUSED fail-closed (never adjudicated) ──

test("fail-closed: a source-blind reader-document-only input is refused, not adjudicated", () => {
  const sourceBlind = {
    role: "source-verifier",
    chapterDocument: "reader-facing prose only — no packet, no sidecar, no plan, no anchors",
    requiredSourceUnitIds: [],
  };
  assert.equal(isSourceReviewPacketEquipped(sourceBlind), false);
  assert.throws(() => assertSourceReviewPacketEquipped(sourceBlind), SourceProjectionBoundaryError);
  const errors = sourceReviewPacketEquippedErrors(sourceBlind);
  assert.ok(errors.some((e) => e.includes("sourcePacket")), errors.join("\n"));
});

test("fail-closed: the dieted WRITER projection substituted for the packet is refused (not accidentally the reviewer surface)", () => {
  const packet = evidencePacket();
  const dieted = {
    role: "source-verifier",
    chapterDocument: "prose",
    sourcePlanLicense: ["a license line"],
    sourcePacket: writerPacketProjection(packet), // the dieted writer view masquerading as the packet
    sourceSidecar: NON_V2_SIDECAR,
    anchorCatalog: writerPacketProjection(packet).allowedAnchors, // bare id strings
    requiredSourceUnitIds: [],
  };
  assert.equal(isSourceReviewPacketEquipped(dieted), false);
  const errors = sourceReviewPacketEquippedErrors(dieted);
  // The writer diet has no root provenance and no case allowedUses/forbiddenUses,
  // and its anchors are bare id strings — each is caught.
  assert.ok(errors.some((e) => e.includes("sourceSidecarPath")), errors.join("\n"));
  assert.ok(errors.some((e) => e.includes("allowedUses") || e.includes("namedCases")), errors.join("\n"));
  assert.ok(errors.some((e) => e.includes("bare anchor id strings")), errors.join("\n"));
});

test("fail-closed: a missing sidecar refuses (a source blocker is unfalsifiable without it)", () => {
  const packet = evidencePacket();
  const reviewPacket = assembleSourceReviewPacket(fxChapter(), freshCasePlan(packet), packet, NON_V2_SIDECAR, packet.allowedAnchors);
  const noSidecar = { ...reviewPacket, sourceSidecar: null };
  assert.equal(isSourceReviewPacketEquipped(noSidecar), false);
  assert.ok(sourceReviewPacketEquippedErrors(noSidecar).some((e) => e.includes("sourceSidecar")));
});

// ── 5. equipped → anchored source_bound case adjudicable SUPPORTED (no false flag) ──

test("equipped: an anchored source_bound case is adjudicable SUPPORTED (the source-blind invented-detail false positive is unreachable)", async () => {
  const packet = evidencePacket();
  const plan = freshCasePlan(packet);
  const chapter = fxChapter();

  // The anchored source_bound case is a REQUIRED source unit.
  const required = computeRequiredSourceUnitIds(plan);
  assert.deepEqual(required, ["unit.case.ch01.ex.a"]);

  // Injected semantic verdict: with the source evidence in hand, the reviewer
  // marks the anchored case SUPPORTED (NOT invented_detail). Zero live calls.
  const reply = JSON.stringify({
    schema: "source-integrity-review-v1",
    units: [{
      unitId: "unit.case.ch01.ex.a",
      expectedOrigin: "source_bound",
      expectedForm: "case",
      claimStrengthExpected: "descriptive",
      visibleRegister: "clearly_sourced",
      supportStatus: "SUPPORTED",
      framingAdequate: null,
      claimStrengthFit: true,
      namedSpecificityAllowed: true,
      chapterEvidenceSpans: ["the named case"],
      sourceEvidenceSpans: ["a documented instance for ch01.ex.a"],
      findings: [],
    }],
    result: "PASS",
    blockingFindingIds: [],
    rationale: "the anchored case is supported by the provided source evidence",
  });
  const spawn: SourceIntegritySpawnFn = () => ({ finalMessage: reply });

  const out = await runSourceIntegrityReview(laneInput(packet, plan, chapter), { spawn });
  assert.equal(out.result, "PASS", "an anchored source_bound case adjudicates SUPPORTED, not invented");
  assert.equal(out.review.units[0].supportStatus, "SUPPORTED");
  assert.ok(!out.review.units[0].findings.some((f) => f.category === "invented_detail"), "no false invented-detail flag when equipped");
  // The equipped verdict carries all FIVE binding hashes (impl-instruction 2:
  // a verdict produced without the source artifacts is not-fresh), and the
  // source-use-plan hash matches the plan it was produced under.
  assert.equal(out.review.sourceUsePlanSha256, sourceUsePlanHash(plan));
  for (const h of [
    out.review.chapterContentSha256, out.review.sourceUsePlanSha256, out.review.sourcePacketSha256,
    out.review.sidecarSha256, out.review.schemaSha256,
  ]) {
    assert.ok(typeof h === "string" && h.length > 0, "every binding hash is present and non-empty");
  }
});

// ── 6. manifest regeneration byte-check (tool-regenerated, 18 contracts) ────────

test("manifest byte-check: contract-manifest.json is the tool output for the 18 live descriptors (no hand-edit)", () => {
  const frozen = loadFrozenManifest();
  const expected = JSON.stringify(computeContractManifest(frozen.frozenAtIso), null, 2) + "\n";
  const onDisk = readFileSync(CONTRACT_MANIFEST_PATH, "utf8");
  assert.equal(onDisk, expected, "contract-manifest.json drifted from the generator output — run `npx tsx src/contracts/generateManifest.ts`");
  assert.equal(frozen.contracts.length, 18);
  assert.ok(frozen.contracts.some((c) => c.name === "source-projection-boundary" && c.ownerPrompt === "WP-305"));
});

// ── 7. ontology change stales the bound source review ──────────────────────────

test("freeze: an ontology change (plan origin/form/claim-strength) stales the bound source review", () => {
  const packet = evidencePacket();
  const plan = freshCasePlan(packet);
  const planSha = sourceUsePlanHash(plan);

  // A review fresh against plan A.
  const freshReview: SourceIntegrityReviewV1 = {
    schema: "source-integrity-review-v1",
    reviewerRole: "source-integrity",
    chapterContentSha256: "chapSha",
    sourceUsePlanSha256: planSha,
    sourcePacketSha256: "pktSha",
    sidecarSha256: "sideSha",
    schemaSha256: "schemaSha",
    units: [],
    result: "PASS",
    blockingFindingIds: [],
    rationale: "",
  };
  assert.equal(sourceReviewIsFresh(freshReview, "chapSha", planSha, "pktSha", "sideSha", "schemaSha"), true);

  // Mutate the ONTOLOGY on the plan (origin source_bound → constructed): the plan
  // hash changes, so the review bound to the old hash is no longer fresh.
  const mutated = { ...plan, units: [{ ...plan.units[0], origin: "constructed" as const, framingRequired: true }] };
  const mutatedSha = sourceUsePlanHash(mutated);
  assert.notEqual(mutatedSha, planSha, "an ontology field change moves the source-use-plan hash");
  assert.equal(sourceReviewIsFresh(freshReview, "chapSha", mutatedSha, "pktSha", "sideSha", "schemaSha"), false);
});

// ── 8. the boundary contract is registered + coherent ──────────────────────────

test("the source-projection-boundary descriptor is registered, v1, WP-305, and pins the writer-stripped evidence", () => {
  assert.equal(SOURCE_PROJECTION_BOUNDARY_CONTRACT.name, "source-projection-boundary");
  assert.equal(SOURCE_PROJECTION_BOUNDARY_CONTRACT.version, 1);
  assert.equal(SOURCE_PROJECTION_BOUNDARY_CONTRACT.ownerPrompt, "WP-305");
  // The frozen field list and the runtime constant are the same source of truth.
  for (const f of ["allowedUses", "forbiddenUses", "sourceSidecarPath", "sourceHash"]) {
    assert.ok(WRITER_STRIPPED_SOURCE_EVIDENCE.includes(f), `${f} must be a writer-stripped source-evidence field`);
  }
});
