/**
 * rubricMetrics — the deterministic half of the book-score rubric, ported
 * verbatim from the canonical scorer so the pipeline measures a book against
 * the SAME ruler that scores it after publish.
 *
 * WHY THIS EXISTS
 * ---------------
 * Generated books are graded post-publish by `.claude/skills/book-score/score.py`
 * (+ `compose.py`) against `RUBRIC.md`. score.py's deterministic metrics —
 * Flesch Reading Ease (rubric band 72–84), FK grade (~7–8), Gunning Fog,
 * three-plus-syllable %, sentence rhythm, distractor-tell %, transfer ratio,
 * clean-memorable-line count, house-tic density, nominalization % — existed
 * NOWHERE in the pipeline, so books were only measured *after* they shipped.
 * the-power-of-moments shipped at Flesch 63.9 / 72% distractor-tell and scored
 * 74.7/100 (rank 95/98) with no pre-publish signal.
 *
 * This module is the single source of truth those metrics were missing. Later
 * prompts (P02–P04, P06) consume it; the whole point is FORMULA PARITY with
 * score.py — a "similar" re-implementation would be a third, conflicting ruler.
 * Every formula, tokenizer, threshold, and word list below is a faithful port
 * of score.py at .claude/skills/book-score/score.py. Parity is pinned by
 * tests/rubric-metrics.test.ts against tests/fixtures/rubric-metrics-parity.json,
 * which is generated by importing score.py's own functions (scratch/gen-rubric-parity.py).
 *
 * PARITY STATUS (per metric — max observed delta vs score.py in the fixture)
 * -------------------------------------------------------------------------
 *   fleschReadingEase ....... EXACT formula; float parity within ±1e-9.
 *   fkGrade ................. EXACT formula; float parity within ±1e-9.
 *   gunningFog .............. EXACT formula; float parity within ±1e-9.
 *   pctThreePlusSyllableWords EXACT; float parity within ±1e-9.
 *   sentenceRhythm .......... EXACT (population stdev, matches statistics.pstdev).
 *   distractorTell / Rate ... EXACT (char-length longest-unique rule; see note 1).
 *   isTransferQuestion ...... prompt-cue half of score.py's classifier (see note 2).
 *   transferRatio ........... EXACT port of score.py transfer_ratio (blooms ∪ cue).
 *   memorableLineClean/Count  EXACT (≤14-word rule; see note 3).
 *   houseTicDensity ......... EXACT (per-text occurrence count of the tic list).
 *   nominalizationRate ...... EXACT for ASCII prose (see note 4).
 *
 * DIVERGENCES (documented, no silent drift)
 * -----------------------------------------
 *  (1) DISTRACTOR-TELL LEXICON. RUBLIC.md §3 describes the tell as "keyed answer
 *      is the longest/MOST-HEDGED". score.py implements ONLY the longest-unique
 *      half (by CHARACTER length) and ships no hedge lexicon. We port score.py
 *      faithfully (longest-unique-by-chars); the hedge-lexicon half is
 *      unimplemented in the canonical scorer, so implementing it here would
 *      create the very third ruler this module exists to prevent. If a hedge
 *      signal is ever wanted, add it to score.py FIRST, then re-port.
 *  (2) isTransferQuestion is the deterministic *prompt-cue* sub-heuristic only
 *      (score.py's `cue` term). score.py's full per-question transfer test is
 *      `bloomsLevel ∈ {apply,analyze,analyse,evaluate,create}  OR  cue`, which
 *      transferRatio() ports exactly. isTransferQuestion's optional chapterText
 *      arg is accepted for the RUBRIC-documented "answerable from a NEW scenario"
 *      framing but is unused by score.py, so it does not affect the verdict here.
 *  (3) MEMORABLE-LINE CLEANLINESS. score.py's ONLY deterministic cleanliness
 *      criterion is word-count ≤ 14; RUBRIC's fuller "portable, complete-claim
 *      aphorism" definition is a [P] panel judgement, not scriptable. We port
 *      the ≤14-word rule. (Faithful edge: an empty line has 0 words → counts as
 *      "clean" in score.py; we match that.)
 *  (4) NOMINALIZATION uses JS `\w` (ASCII) vs Python3 `\w` (Unicode). Identical
 *      on ASCII prose (all book prose); a token containing non-ASCII word chars
 *      could differ. No divergence observed on any fixture.
 *  (5) readingLevel.ts (src/critics/readingLevel.ts) has a DIFFERENT syllable
 *      counter (short-word shortcut, -ed/-es/-e stripping, leading-y strip) and
 *      a different word regex (`\b[A-Za-z'-]+\b`). It therefore disagrees with
 *      score.py's FK. This module intentionally does NOT reuse it; P02 owns the
 *      call-site migration. Measured FK deltas vs readingLevel over the fixtures
 *      are recorded by the "divergence vs readingLevel.ts" test.
 *
 * Pure module: no fs, no network, no npm deps.
 */

// ---- tokenizers (ported: score.py syllables / words / sentences) ----------

const VOWELS = "aeiouy";

/** score.py `syllables(word)` — vowel-group count, drop a silent trailing 'e'. */
export function syllables(word: string): number {
  const w = word.toLowerCase().replace(/[^a-z]/g, "");
  if (!w) return 0;
  let count = 0;
  let prev = false;
  for (const ch of w) {
    const v = VOWELS.includes(ch);
    if (v && !prev) count += 1;
    prev = v;
  }
  if (w.endsWith("e") && count > 1) count -= 1;
  return Math.max(1, count);
}

/** score.py `words(text)` — `[A-Za-z][A-Za-z'-]*` (token must START with a letter;
 *  only ASCII apostrophe/hyphen continue it — a Unicode ’ splits the token). */
export function words(text: string): string[] {
  return text.match(/[A-Za-z][A-Za-z'-]*/g) ?? [];
}

/** score.py `sentences(text)` — split after . ! ? + whitespace, keep parts with a letter. */
export function sentences(text: string): string[] {
  return text
    .trim()
    .split(/(?<=[.!?])\s+/)
    .filter((p) => /[A-Za-z]/.test(p));
}

// ---- readability (ported: score.py readability(text)) ---------------------

export type ReadabilityMetrics = {
  flesch: number;
  fk: number;
  fog: number;
  pct3syl: number;
  sylword: number;
  wps: number;
};

/** score.py `readability(text)`; returns null when there are no words or no
 *  sentences (score.py returns None). Computed once so every derived getter
 *  below shares one tokenization pass — no formula drift between them. */
export function readabilityMetrics(text: string): ReadabilityMetrics | null {
  const sents = sentences(text);
  const ws = words(text);
  const nw = ws.length;
  const ns = sents.length;
  if (nw === 0 || ns === 0) return null;
  const syl = ws.map(syllables);
  const complex3 = syl.filter((s) => s >= 3).length;
  const wps = nw / ns;
  const spw = syl.reduce((a, b) => a + b, 0) / nw;
  return {
    flesch: 206.835 - 1.015 * wps - 84.6 * spw,
    fk: 0.39 * wps + 11.8 * spw - 15.59,
    fog: 0.4 * (wps + (100 * complex3) / nw),
    pct3syl: (100 * complex3) / nw,
    sylword: spw,
    wps,
  };
}

/** Flesch Reading Ease (rubric band 72–84). NaN on degenerate input (score.py None). */
export function fleschReadingEase(text: string): number {
  return readabilityMetrics(text)?.flesch ?? NaN;
}

/** Flesch-Kincaid grade (rubric ~7–8). NaN on degenerate input. */
export function fkGrade(text: string): number {
  return readabilityMetrics(text)?.fk ?? NaN;
}

/** Gunning Fog index. NaN on degenerate input. */
export function gunningFog(text: string): number {
  return readabilityMetrics(text)?.fog ?? NaN;
}

/** Percent of words with ≥3 syllables. NaN on degenerate input. */
export function pctThreePlusSyllableWords(text: string): number {
  return readabilityMetrics(text)?.pct3syl ?? NaN;
}

// ---- sentence rhythm (ported: score.py rhythm(text)) ----------------------

export type SentenceRhythm = {
  /** coefficient of variation = population stdev / mean of sentence word-lengths */
  cv: number;
  /** percent of sentences shorter than 6 words */
  shortPct: number;
  /** longest sentence, in words */
  maxLen: number;
};

/** score.py `rhythm(text)`; null when fewer than 2 non-empty sentences (score.py None). */
export function sentenceRhythm(text: string): SentenceRhythm | null {
  const lens = sentences(text)
    .map((s) => words(s).length)
    .filter((l) => l > 0);
  if (lens.length < 2) return null;
  const mean = lens.reduce((a, b) => a + b, 0) / lens.length;
  const variance = lens.reduce((a, l) => a + (l - mean) ** 2, 0) / lens.length; // population
  const pstdev = Math.sqrt(variance);
  return {
    cv: mean ? pstdev / mean : 0,
    shortPct: (100 * lens.filter((l) => l < 6).length) / lens.length,
    maxLen: Math.max(...lens),
  };
}

// ---- house tics + nominalization (ported: score.py HOUSE / NOM inline) -----

/** score.py HOUSE list — bland house-voice tells, counted per chapter prose. */
export const HOUSE_TIC_PHRASES = [
  "the point is",
  "here is the thing",
  "the truth is",
  "make no mistake",
  "at the end of the day",
  "the bottom line",
] as const;

function countOccurrences(haystack: string, needle: string): number {
  if (!needle) return 0;
  let count = 0;
  let i = 0;
  for (;;) {
    const at = haystack.indexOf(needle, i);
    if (at === -1) break;
    count += 1;
    i = at + needle.length; // non-overlapping, matches Python str.count
  }
  return count;
}

/** score.py `sum(text.lower().count(h) for h in HOUSE)` — total tic occurrences
 *  in the given text (per-chapter this is a raw count; the scorer means it
 *  across sampled chapters). */
export function houseTicDensity(text: string): number {
  const lower = text.toLowerCase();
  return HOUSE_TIC_PHRASES.reduce((sum, h) => sum + countOccurrences(lower, h), 0);
}

/** score.py `NOM = /\w+(tion|ment|ness|ity|ance|ence)\b/i` */
const NOM = /\w+(?:tion|ment|ness|ity|ance|ence)\b/gi;

/** score.py `100 * len(NOM.findall(text)) / len(words(text)) if words else 0`. */
export function nominalizationRate(text: string): number {
  const ws = words(text);
  if (ws.length === 0) return 0;
  const matches = text.match(NOM) ?? [];
  return (100 * matches.length) / ws.length;
}

// ---- quiz: distractor-tell (ported: score.py distractor_tell) -------------

export type QuizQuestion = {
  choices?: unknown;
  correctIndex?: unknown;
  bloomsLevel?: unknown;
  prompt?: unknown;
};

/** Port of Python `int(x)`: truncates a finite number toward zero; a string must
 *  be a pure integer literal (int("1.5") raises → we reject); anything else → null
 *  (score.py hits its except/range guard and SKIPS the question). */
function pythonInt(raw: unknown): number | null {
  if (typeof raw === "number") {
    return Number.isFinite(raw) ? Math.trunc(raw) : null;
  }
  if (typeof raw === "string") {
    const s = raw.trim();
    return /^[+-]?\d+$/.test(s) ? parseInt(s, 10) : null;
  }
  return null;
}

/** The scorable verdict for ONE question:
 *   true  = keyed answer is the uniquely longest choice (by character count)
 *   false = it is not
 *   null  = question is excluded from the tell rate (no choices / invalid index),
 *           exactly as score.py drops it from the denominator. */
function distractorTellEval(q: QuizQuestion): boolean | null {
  const choices = Array.isArray(q.choices) ? (q.choices as unknown[]) : [];
  if (choices.length === 0) return null;
  const ci = pythonInt(q.correctIndex);
  if (ci === null || !(ci >= 0 && ci < choices.length)) return null;
  const lens = choices.map((ch) => String(ch).length);
  const maxLen = Math.max(...lens);
  return lens[ci] === maxLen && lens.filter((l) => l === maxLen).length === 1;
}

/** Per-question distractor-tell with human-readable reasons. `tell` is false for
 *  excluded questions (see distractorTellRate for the rate-correct exclusion). */
export function distractorTell(q: { choices: string[]; correctIndex: number } | QuizQuestion): {
  tell: boolean;
  reasons: string[];
} {
  const verdict = distractorTellEval(q as QuizQuestion);
  if (verdict === null) {
    return {
      tell: false,
      reasons: ["excluded from tell rate: empty choices or non-integer/out-of-range correctIndex"],
    };
  }
  if (verdict) {
    const ci = pythonInt((q as QuizQuestion).correctIndex);
    return {
      tell: true,
      reasons: [`keyed answer (choice ${ci}) is the uniquely longest choice by character count`],
    };
  }
  return { tell: false, reasons: ["keyed answer is not the uniquely longest choice"] };
}

/** score.py `distractor_tell` rate = 100 * tell / scorable. NaN when nothing is
 *  scorable (score.py None). Percentage 0..100, matching score.py's units. */
export function distractorTellRate(questions: QuizQuestion[]): number {
  let tell = 0;
  let tot = 0;
  for (const q of questions) {
    const v = distractorTellEval(q);
    if (v === null) continue;
    tot += 1;
    if (v) tell += 1;
  }
  return tot ? (100 * tell) / tot : NaN;
}

// ---- quiz: transfer ratio (ported: score.py transfer_ratio) ---------------

/** score.py APPLY set — Bloom's levels that count as transfer on their own. */
const APPLY = new Set(["apply", "analyze", "analyse", "evaluate", "create"]);

/** score.py cue lexicon — scenario markers in the prompt. */
export const TRANSFER_CUES = [
  "you are",
  "imagine",
  "suppose",
  "a colleague",
  "your team",
  "scenario",
  "consider a",
] as const;

/** Deterministic prompt-cue half of score.py's transfer test (its `cue` term).
 *  chapterText is accepted for the RUBRIC "new scenario" framing but is unused
 *  by score.py, so it does not change the verdict (see docblock note 2). */
export function isTransferQuestion(prompt: string, _chapterText?: string): boolean {
  const p = (prompt ?? "").toLowerCase();
  return TRANSFER_CUES.some((w) => p.includes(w));
}

/** score.py `transfer_ratio` = 100 * (blooms∈APPLY ∪ cue) / total. NaN when there
 *  are no questions (score.py None). Percentage 0..100. */
export function transferRatio(questions: QuizQuestion[]): number {
  if (questions.length === 0) return NaN;
  let apply = 0;
  for (const q of questions) {
    const bl = String(q.bloomsLevel ?? "").toLowerCase();
    const cue = isTransferQuestion(String(q.prompt ?? ""));
    if (APPLY.has(bl) || cue) apply += 1;
  }
  return (100 * apply) / questions.length;
}

// ---- retention: memorable lines (ported: score.py memorable_lines) --------

/** score.py cleanliness rule: a memorable line is "clean" iff ≤14 words. */
export function memorableLineClean(line: string): boolean {
  return words(line).length <= 14;
}

/** Count of clean (≤14-word) lines. score.py's per-chapter `clean` tally. */
export function cleanMemorableLineCount(lines: string[]): number {
  return lines.filter(memorableLineClean).length;
}

// ---- rubric numeric targets ------------------------------------------------

/**
 * The rubric's published NUMERIC targets (RUBRIC.md §2/§3/§11). Only these
 * metrics carry an explicit numeric threshold in the rubric; fog, pct3syl,
 * sentence rhythm, house-tic density, and nominalization are diagnostic
 * signals score.py reports without a hard rubric cutoff. Rates are percentages
 * (0..100), matching score.py's units.
 */
export const RUBRIC_METRIC_TARGETS = {
  /** §11 Beginner-friendliness — Flesch Reading Ease band. */
  fleschReadingEase: { min: 72, max: 84 },
  /** §11 — Flesch-Kincaid grade (rubric prose: "~7–8"). */
  fkGrade: { min: 7, max: 8 },
  /** §3 Quizzes — distractor tell, percent; baseline 68%, goal < 20%. */
  distractorTellRatePct: { max: 20 },
  /** §3 Quizzes — transfer ratio, percent; goal > 70%. */
  transferRatioPct: { min: 70 },
  /** §2 Retention — clean (≤14-word) memorable lines per chapter; ≥2. */
  cleanMemorableLinesPerChapter: { min: 2 },
} as const;
