import type { ProgressPageData } from "./progressTypes";

export const mockProgressData: ProgressPageData = {
  user: {
    name: "Will",
    readerLevel: "Curious Reader",
    readerLevelProgress: 0,
    flowPoints: 150,
    isPro: false,
  },
  todayGoal: {
    targetMinutes: 20,
    completedMinutes: 3,
    stepsCompletedToday: 0,
    totalStepsToday: 4,
  },
  streak: {
    currentDays: 2,
    bestDays: 2,
    lastActiveDate: new Date().toISOString(),
    freezesEquipped: 1,
    freezesAvailable: 2,
    consistencyLast30Days: 7,
    daysActiveLast7: 2,
  },
  weekSummary: {
    timeReadMinutes: 50,
    previousWeekMinutes: 35,
    chaptersCompleted: 0,
    previousWeekChapters: 0,
    quizAccuracy: null,
    previousWeekQuizAccuracy: null,
    weekStartDate: "2026-03-16",
  },
  activeBooks: [
    {
      id: "so-good",
      title: "So Good They Can't Ignore You",
      author: "Cal Newport",
      coverUrl: "/covers/so-good.jpg",
      totalChapters: 15,
      completedChapters: 0,
      currentChapterNumber: 1,
      currentChapterTitle: "The Rule of Remarkability",
      currentStep: "summary",
      currentStepNumber: 1,
      lastActivity: "Browsed",
      lastActivityDate: new Date().toISOString(),
      readersCount: 347,
      resumeChapterId: "ch-01",
    },
    {
      id: "never-split",
      title: "Never Split the Difference",
      author: "Chris Voss with Tahl Raz",
      coverUrl: "/covers/never-split.jpg",
      totalChapters: 10,
      completedChapters: 0,
      currentChapterNumber: 1,
      currentChapterTitle: "The New Rules",
      currentStep: "summary",
      currentStepNumber: 1,
      lastActivity: "CH.01 The New Rules",
      lastActivityDate: new Date().toISOString(),
      readersCount: 512,
      resumeChapterId: "ch-01",
    },
  ],
  completedBooks: [],
  dailyQuests: [
    {
      id: "q1",
      title: "Read for 10 minutes",
      icon: "\u{1F4D6}",
      current: 3,
      target: 10,
      type: "progress",
      completed: false,
    },
    {
      id: "q2",
      title: "Complete a quiz",
      icon: "\u{1F9E0}",
      current: 0,
      target: 1,
      type: "boolean",
      completed: false,
    },
    {
      id: "q3",
      title: "Review 5 concepts",
      icon: "\u{1F504}",
      current: 0,
      target: 5,
      type: "progress",
      completed: false,
    },
  ],
  questBonusFP: 75,
  reviews: {
    overdueCount: 0,
    dueTodayCount: 0,
    upcomingThisWeekCount: 0,
    totalConceptsLearned: 0,
    forecast: [],
  },
  readingActivity: {
    days: [
      { date: "2026-03-21", minutes: 25, chapters: 0 },
      { date: "2026-03-22", minutes: 3, chapters: 0 },
    ],
    totalDaysWithData: 2,
    todayHourly: Array.from({ length: 24 }, (_, h) => ({ hour: h, minutes: 0 })),
  },
  nextMilestones: [
    {
      id: "first-steps",
      name: "First Steps",
      icon: "\u{1F3C5}",
      description: "Complete 1 chapter",
      current: 0,
      target: 1,
    },
    {
      id: "flame-keeper",
      name: "Flame Keeper",
      icon: "\u{1F525}",
      description: "Maintain a 7-day streak",
      current: 2,
      target: 7,
    },
    {
      id: "quiz-ace",
      name: "Quiz Ace",
      icon: "\u{1F9E0}",
      description: "Score 90%+ on 3 quizzes",
      current: 0,
      target: 3,
    },
  ],
};
