/**
 * Parity + edge-case tests for src/metrics/rubricMetrics.ts.
 *
 * The parity fixture (tests/fixtures/rubric-metrics-parity.json) is generated by
 * scratch/gen-rubric-parity.py, which imports the CANONICAL scorer
 * (.claude/skills/book-score/score.py) and records ITS OWN outputs. Asserting the
 * TS port against that fixture is what pins formula parity: the port and score.py
 * are the same ruler, not two similar ones.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { test } from "./harness.js";
import {
  fleschReadingEase,
  fkGrade,
  gunningFog,
  pctThreePlusSyllableWords,
  sentenceRhythm,
  readabilityMetrics,
  nominalizationRate,
  houseTicDensity,
  distractorTell,
  distractorTellRate,
  transferRatio,
  isTransferQuestion,
  memorableLineClean,
  cleanMemorableLineCount,
  syllables,
  words,
  sentences,
  RUBRIC_METRIC_TARGETS,
  HOUSE_TIC_PHRASES,
  TRANSFER_CUES,
} from "../src/metrics/rubricMetrics.js";
// readingLevel.ts is the DIVERGENT existing FK impl — measured, not asserted-equal.
import { fleschKincaid, countSyllables } from "../src/critics/readingLevel.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

type ReadabilityDict = {
  flesch: number;
  fk: number;
  fog: number;
  pct3syl: number;
  sylword: number;
  wps: number;
} | null;

type Fixture = {
  readability: Array<{
    name: string;
    text: string;
    readability: ReadabilityDict;
    rhythm: { cv: number; shortPct: number; maxLen: number } | null;
    nominal: number;
    houseTic: number;
    houseTicText?: string;
  }>;
  distractorTell: Array<{ name: string; question: any; tell: boolean | null }>;
  distractorTellRate: Array<{ name: string; questions: any[]; ratePct: number | null }>;
  transfer: Array<{ name: string; questions: any[]; ratePct: number | null }>;
  isTransferQuestion: Array<{ prompt: string; expected: boolean }>;
  memorable: Array<{ name: string; lines: string[]; cleanCount: number; total: number }>;
};

const fx: Fixture = JSON.parse(
  readFileSync(resolve(__dirname, "fixtures", "rubric-metrics-parity.json"), "utf8"),
);

const TOL = 1e-9; // exact-port tolerance (fixture stores full-precision Python floats)

function approx(actual: number, expected: number, tol: number, msg: string): void {
  assert.ok(
    Math.abs(actual - expected) <= tol,
    `${msg}: expected ${expected}, got ${actual} (Δ=${Math.abs(actual - expected)} > ${tol})`,
  );
}

// ---------------------------------------------------------------------------
// PARITY: readability / rhythm / nominalization / house tics
// ---------------------------------------------------------------------------

test("readability parity vs score.py (flesch, fk, fog, pct3syl, sylword, wps)", () => {
  for (const c of fx.readability) {
    const r = readabilityMetrics(c.text);
    if (c.readability === null) {
      assert.equal(r, null, `${c.name}: expected null readability`);
      assert.ok(Number.isNaN(fleschReadingEase(c.text)), `${c.name}: flesch NaN`);
      assert.ok(Number.isNaN(fkGrade(c.text)), `${c.name}: fk NaN`);
      assert.ok(Number.isNaN(gunningFog(c.text)), `${c.name}: fog NaN`);
      assert.ok(Number.isNaN(pctThreePlusSyllableWords(c.text)), `${c.name}: pct3syl NaN`);
      continue;
    }
    assert.ok(r, `${c.name}: expected non-null readability`);
    approx(r!.flesch, c.readability.flesch, TOL, `${c.name} flesch`);
    approx(r!.fk, c.readability.fk, TOL, `${c.name} fk`);
    approx(r!.fog, c.readability.fog, TOL, `${c.name} fog`);
    approx(r!.pct3syl, c.readability.pct3syl, TOL, `${c.name} pct3syl`);
    approx(r!.sylword, c.readability.sylword, TOL, `${c.name} sylword`);
    approx(r!.wps, c.readability.wps, TOL, `${c.name} wps`);
    // the standalone getters must agree with the bundle
    approx(fleschReadingEase(c.text), c.readability.flesch, TOL, `${c.name} fleschReadingEase()`);
    approx(fkGrade(c.text), c.readability.fk, TOL, `${c.name} fkGrade()`);
    approx(gunningFog(c.text), c.readability.fog, TOL, `${c.name} gunningFog()`);
    approx(
      pctThreePlusSyllableWords(c.text),
      c.readability.pct3syl,
      TOL,
      `${c.name} pctThreePlusSyllableWords()`,
    );
  }
});

test("sentenceRhythm parity vs score.py (cv, shortPct, maxLen)", () => {
  for (const c of fx.readability) {
    const y = sentenceRhythm(c.text);
    if (c.rhythm === null) {
      assert.equal(y, null, `${c.name}: expected null rhythm`);
      continue;
    }
    assert.ok(y, `${c.name}: expected non-null rhythm`);
    approx(y!.cv, c.rhythm.cv, TOL, `${c.name} rhythm.cv`);
    approx(y!.shortPct, c.rhythm.shortPct, TOL, `${c.name} rhythm.shortPct`);
    assert.equal(y!.maxLen, c.rhythm.maxLen, `${c.name} rhythm.maxLen`);
  }
});

test("nominalizationRate parity vs score.py", () => {
  for (const c of fx.readability) {
    approx(nominalizationRate(c.text), c.nominal, TOL, `${c.name} nominal`);
  }
});

test("houseTicDensity parity vs score.py (exact counts)", () => {
  for (const c of fx.readability) {
    const text = c.houseTicText ?? c.text;
    assert.equal(houseTicDensity(text), c.houseTic, `${c.name} houseTic`);
  }
});

// ---------------------------------------------------------------------------
// PARITY: quiz metrics
// ---------------------------------------------------------------------------

test("distractorTell parity vs score.py (per-question verdict)", () => {
  for (const c of fx.distractorTell) {
    const got = distractorTell(c.question);
    // score.py excludes null cases; per-question rate encodes that as NaN.
    const rate = distractorTellRate([c.question]);
    if (c.tell === null) {
      assert.ok(Number.isNaN(rate), `${c.name}: excluded question → rate NaN`);
      assert.equal(got.tell, false, `${c.name}: excluded → tell false`);
      assert.match(got.reasons.join(" "), /excluded/i, `${c.name}: reason names exclusion`);
    } else {
      assert.equal(got.tell, c.tell, `${c.name}: tell verdict`);
      approx(rate, c.tell ? 100 : 0, TOL, `${c.name}: single-question rate`);
    }
  }
});

test("distractorTellRate parity vs score.py (NaN when nothing scorable)", () => {
  for (const c of fx.distractorTellRate) {
    const got = distractorTellRate(c.questions);
    if (c.ratePct === null) {
      assert.ok(Number.isNaN(got), `${c.name}: expected NaN`);
    } else {
      approx(got, c.ratePct, TOL, `${c.name}: rate`);
    }
  }
});

test("transferRatio parity vs score.py (blooms ∪ cue; NaN when empty)", () => {
  for (const c of fx.transfer) {
    const got = transferRatio(c.questions);
    if (c.ratePct === null) {
      assert.ok(Number.isNaN(got), `${c.name}: expected NaN`);
    } else {
      approx(got, c.ratePct, TOL, `${c.name}: transfer rate`);
    }
  }
});

test("isTransferQuestion parity vs score.py cue lexicon", () => {
  for (const c of fx.isTransferQuestion) {
    assert.equal(isTransferQuestion(c.prompt), c.expected, `prompt="${c.prompt}"`);
  }
});

test("memorable-line cleanliness parity vs score.py (≤14 words)", () => {
  for (const c of fx.memorable) {
    assert.equal(cleanMemorableLineCount(c.lines), c.cleanCount, `${c.name}: clean count`);
    assert.equal(c.lines.length, c.total, `${c.name}: total sanity`);
  }
});

// ---------------------------------------------------------------------------
// EDGE-CASE unit tests (independent of fixture)
// ---------------------------------------------------------------------------

test("tokenizers: syllables edge cases match score.py rules", () => {
  assert.equal(syllables(""), 0); // no letters
  assert.equal(syllables("123"), 0); // stripped to empty
  assert.equal(syllables("a"), 1);
  assert.equal(syllables("the"), 1);
  assert.equal(syllables("cake"), 1); // silent trailing e drops the group
  assert.equal(syllables("rhythm"), 1); // no vowel group → floored to 1
  assert.equal(syllables("bee"), 1); // ends in e, count>1 → 1
  assert.equal(syllables("habit"), 2);
});

test("tokenizers: words requires a leading letter; ASCII apostrophe/hyphen continue", () => {
  assert.deepEqual(words("it's a well-known fox"), ["it's", "a", "well-known", "fox"]);
  // a Unicode right-quote is NOT a word char → splits the token (score.py behavior)
  assert.deepEqual(words("don’t"), ["don", "t"]);
  assert.deepEqual(words("2020 and 15"), ["and"]); // tokens must START with a letter
  assert.deepEqual(words(""), []);
});

test("tokenizers: sentences split on . ! ? + whitespace and keep lettered parts", () => {
  assert.deepEqual(sentences("Go. Run! Win?"), ["Go.", "Run!", "Win?"]);
  assert.deepEqual(sentences("   "), []);
  assert.deepEqual(sentences("42. 7."), []); // no letters → dropped
});

test("degenerate readability inputs return NaN / null (score.py None)", () => {
  assert.ok(Number.isNaN(fleschReadingEase("")));
  assert.ok(Number.isNaN(fkGrade("   ")));
  assert.ok(Number.isNaN(gunningFog("123 456")));
  assert.equal(readabilityMetrics(""), null);
  assert.equal(sentenceRhythm("only one sentence here"), null); // <2 sentences
});

test("memorableLineClean: ≤14 words clean, 15 not, empty is clean (faithful edge)", () => {
  assert.equal(memorableLineClean("one two three"), true);
  assert.equal(
    memorableLineClean("one two three four five six seven eight nine ten eleven twelve thirteen fourteen"),
    true,
  );
  assert.equal(
    memorableLineClean(
      "one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen",
    ),
    false,
  );
  assert.equal(memorableLineClean(""), true); // 0 words ≤ 14
});

test("distractorTell: tie for longest is NOT a tell; unique longest key is", () => {
  assert.equal(distractorTell({ choices: ["aaaa", "aaaa", "bb"], correctIndex: 0 }).tell, false);
  assert.equal(distractorTell({ choices: ["bb", "cc", "aaaaa"], correctIndex: 2 }).tell, true);
  // out-of-range / empty → excluded, tell:false with a stated reason
  assert.equal(distractorTell({ choices: ["a", "b"], correctIndex: 9 }).tell, false);
  assert.equal(distractorTell({ choices: [], correctIndex: 0 }).tell, false);
});

test("houseTicDensity + nominalizationRate behave on empty/plain text", () => {
  assert.equal(houseTicDensity(""), 0);
  assert.equal(houseTicDensity("The bottom line is that at the end of the day it works"), 2);
  assert.equal(nominalizationRate(""), 0); // no words → 0, not NaN (score.py branch)
  assert.equal(nominalizationRate("action information"), 100); // 2/2 words end in -tion
});

test("RUBRIC_METRIC_TARGETS encodes the rubric's published numeric bands", () => {
  assert.deepEqual(RUBRIC_METRIC_TARGETS.fleschReadingEase, { min: 72, max: 84 });
  assert.deepEqual(RUBRIC_METRIC_TARGETS.fkGrade, { min: 7, max: 8 });
  assert.equal(RUBRIC_METRIC_TARGETS.distractorTellRatePct.max, 20);
  assert.equal(RUBRIC_METRIC_TARGETS.transferRatioPct.min, 70);
  assert.equal(RUBRIC_METRIC_TARGETS.cleanMemorableLinesPerChapter.min, 2);
  // ported lexicons are present and non-empty
  assert.ok(HOUSE_TIC_PHRASES.length === 6);
  assert.ok(TRANSFER_CUES.length === 7);
});

// ---------------------------------------------------------------------------
// ACCEPTANCE: real-corpus signal (atomic-habits materially easier than POM)
// ---------------------------------------------------------------------------

test("acceptance: atomic-habits reads materially easier than the-power-of-moments", () => {
  const mean = (names: string[]) => {
    const vals = fx.readability
      .filter((c) => names.some((n) => c.name.startsWith(n)))
      .map((c) => (c.readability ? c.readability.flesch : NaN));
    return vals.reduce((a, b) => a + b, 0) / vals.length;
  };
  const ah = mean(["atomic-habits"]);
  const pom = mean(["the-power-of-moments"]);
  assert.ok(ah > 80, `atomic-habits mean Flesch ${ah.toFixed(1)} should be high (>80)`);
  // NOTE: the tracked POM package was regenerated since the 63.9 audit; it now
  // reads ~73.8. The invariant that survives is: atomic-habits reads materially
  // easier than POM by a clear margin (both computed on the SAME score.py ruler).
  assert.ok(pom < ah - 5, `POM mean Flesch ${pom.toFixed(1)} should be materially below AH ${ah.toFixed(1)}`);
});

// ---------------------------------------------------------------------------
// DIVERGENCE: measured, not asserted-equal — readingLevel.ts uses a different
// syllable counter + word regex, so its FK disagrees with score.py's. We record
// the magnitude so P02 (which migrates the call sites) has the number.
// ---------------------------------------------------------------------------

test("divergence vs readingLevel.ts is real and bounded (documented, not parity)", () => {
  let maxDelta = 0;
  let n = 0;
  for (const c of fx.readability) {
    if (!c.readability) continue;
    const mine = fkGrade(c.text);
    const legacy = fleschKincaid(c.text); // rounds to 1dp; different syllable rule
    if (Number.isNaN(mine) || Number.isNaN(legacy)) continue;
    maxDelta = Math.max(maxDelta, Math.abs(mine - legacy));
    n += 1;
  }
  // The two counters genuinely differ (e.g. "table": score.py counts 1 via its
  // silent-trailing-e rule, readingLevel counts 2) — this is WHY the module does
  // not reuse readingLevel.ts.
  assert.ok(Number.isFinite(maxDelta), "max FK delta must be finite");
  assert.equal(syllables("table"), 1, "score.py syllables('table') = 1");
  assert.equal(countSyllables("table"), 2, "readingLevel countSyllables('table') = 2");
  assert.notEqual(countSyllables("table"), syllables("table"),
    "readingLevel countSyllables must differ from score.py syllables (justifies the port)");
  console.log(
    `    [divergence] over ${n} fixtures: max |fkGrade − readingLevel.fleschKincaid| = ${maxDelta.toFixed(2)} grades`,
  );
});
