import type { Badge, BadgeCategory } from "./badge-types";

export const CATEGORY_META: Record<
  Exclude<BadgeCategory, "secret">,
  { title: string; description: string; order: number }
> & Record<"secret", { title: string; description: string; order: number }> = {
  consistency: { title: "Consistency & Streaks", description: "Building the rhythm of a reading life", order: 0 },
  mastery: { title: "Mastery & Depth", description: "Moving beyond the surface into real understanding", order: 1 },
  books: { title: "Books & Completion", description: "Finishing what you start — the hardest part", order: 2 },
  exploration: { title: "Exploration & Discovery", description: "Expanding the boundaries of what you read", order: 3 },
  notes: { title: "Notes & Reflection", description: "The quiet work that makes reading stick", order: 4 },
  secret: { title: "Hidden Achievements", description: "Some badges reveal themselves only through discovery", order: 5 },
};

export const CATEGORY_ORDER: BadgeCategory[] = [
  "consistency",
  "mastery",
  "books",
  "exploration",
  "notes",
  "secret",
];

export const BADGE_DEFINITIONS: Badge[] = [
  // ── Consistency & Streaks ─────────────────────────────────────────────────
  {
    id: "kindling",
    name: "Kindling",
    description: "Build a three-day reading streak",
    narrative: "Three days in a row. It doesn't sound like much, but this is where every reading habit begins. You showed up, and that's the hardest part.",
    category: "consistency",
    tier: "bronze",
    icon: "🔥",
    fpValue: 25,
    isSecret: false,
    criteria: { type: "streak", description: "3-day streak", target: 3 },
    relatedBadgeIds: ["rhythm-silver", "rhythm-gold", "rhythm-platinum"],
    tieredProgression: { currentTier: "bronze", nextTier: "silver", nextTierTarget: 7, nextTierBadgeId: "rhythm-silver" },
    evaluate: (s) => ({ current: Math.min(s.longestStreak, 3), target: 3 }),
  },
  {
    id: "rhythm-silver",
    name: "Rhythm Silver",
    description: "Hold a seven-day streak",
    narrative: "A full week of reading. Seven days of choosing to learn when you could have chosen almost anything else. The rhythm is taking hold.",
    category: "consistency",
    tier: "silver",
    icon: "🔥",
    fpValue: 35,
    isSecret: false,
    criteria: { type: "streak", description: "7-day streak", target: 7 },
    relatedBadgeIds: ["kindling", "rhythm-gold", "rhythm-platinum"],
    tieredProgression: { currentTier: "silver", nextTier: "gold", nextTierTarget: 14, nextTierBadgeId: "rhythm-gold" },
    evaluate: (s) => ({ current: Math.min(s.longestStreak, 7), target: 7 }),
  },
  {
    id: "rhythm-gold",
    name: "Rhythm Gold",
    description: "Hold a fourteen-day streak",
    narrative: "Two weeks of consistent reading. At this point, it's not discipline anymore — it's becoming who you are. The habit is solidifying into identity.",
    category: "consistency",
    tier: "gold",
    icon: "🔥",
    fpValue: 55,
    isSecret: false,
    criteria: { type: "streak", description: "14-day streak", target: 14 },
    relatedBadgeIds: ["rhythm-silver", "rhythm-platinum"],
    tieredProgression: { currentTier: "gold", nextTier: "platinum", nextTierTarget: 30, nextTierBadgeId: "rhythm-platinum" },
    evaluate: (s) => ({ current: Math.min(s.longestStreak, 14), target: 14 }),
  },
  {
    id: "rhythm-platinum",
    name: "Rhythm Platinum",
    description: "Hold a thirty-day streak",
    narrative: "Thirty days. A full month of showing up for your own growth. Most people never get here. You did, and that says everything about your commitment.",
    category: "consistency",
    tier: "platinum",
    icon: "🔥",
    fpValue: 75,
    isSecret: false,
    criteria: { type: "streak", description: "30-day streak", target: 30 },
    relatedBadgeIds: ["rhythm-gold"],
    evaluate: (s) => ({ current: Math.min(s.longestStreak, 30), target: 30 }),
  },
  {
    id: "active-reader",
    name: "Active Reader",
    description: "Read on ten different days",
    narrative: "Ten different days with a book open. Not a streak — just proof that reading has become a natural part of your life, woven into your routine.",
    category: "consistency",
    tier: "unique",
    icon: "📅",
    fpValue: 30,
    isSecret: false,
    criteria: { type: "count", description: "10 distinct reading days", target: 10 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.totalActiveDays, 10), target: 10 }),
  },
  {
    id: "comeback-reader",
    name: "Comeback Reader",
    description: "Miss a day and return quickly instead of drifting away",
    narrative: "You missed a day. Most people would have drifted away entirely. But you came back, and that resilience matters more than any unbroken streak.",
    category: "consistency",
    tier: "unique",
    icon: "🔄",
    fpValue: 20,
    isSecret: false,
    criteria: { type: "boolean", description: "Return within 2 days of breaking streak", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.recoveredAfterMiss, 1), target: 1 }),
  },
  {
    id: "balanced-rhythm",
    name: "Balanced Rhythm",
    description: "Read consistently on both weekdays and weekends",
    narrative: "Weekdays and weekends, work hours and rest hours — you read through all of them. Reading isn't something you squeeze in. It's something you live with.",
    category: "consistency",
    tier: "unique",
    icon: "⚖️",
    fpValue: 25,
    isSecret: false,
    criteria: { type: "compound", description: "Read on at least 3 weekdays + 1 weekend day in a single week", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({
      current: s.weekdayActiveDays >= 3 && s.weekendActiveDays >= 1 ? 1 : 0,
      target: 1,
    }),
  },

  // ── Mastery & Depth ───────────────────────────────────────────────────────
  {
    id: "first-proof",
    name: "First Proof",
    description: "Pass your first chapter quiz — the beginning of earned knowledge",
    narrative: "Your first quiz passed. This is the moment reading stopped being passive — you proved you understood, not just consumed.",
    category: "mastery",
    tier: "bronze",
    icon: "✅",
    fpValue: 15,
    isSecret: false,
    criteria: { type: "count", description: "Pass 1 quiz", target: 1 },
    relatedBadgeIds: ["the-examiner"],
    evaluate: (s) => ({ current: Math.min(s.quizzesPassed, 1), target: 1 }),
  },
  {
    id: "depth-check",
    name: "Depth Check",
    description: "Pass a quiz after reading in Deeper mode",
    narrative: "You chose the harder path and proved you could handle it. Reading in Deeper mode and passing the quiz means genuine comprehension, not just exposure.",
    category: "mastery",
    tier: "unique",
    icon: "🔬",
    fpValue: 25,
    isSecret: false,
    criteria: { type: "count", description: "Pass quiz in Deeper mode", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.quizzesPassedInDeeperMode, 1), target: 1 }),
  },
  {
    id: "perfect-pass",
    name: "Perfect Pass",
    description: "Score a perfect quiz — no guessing, only understanding",
    narrative: "Not a single wrong answer. This wasn't luck — it was the result of reading closely, thinking carefully, and understanding deeply.",
    category: "mastery",
    tier: "unique",
    icon: "💯",
    fpValue: 30,
    isSecret: false,
    criteria: { type: "count", description: "100% on any quiz", target: 1 },
    relatedBadgeIds: ["perfect-series"],
    evaluate: (s) => ({ current: Math.min(s.perfectQuizCount, 1), target: 1 }),
  },
  {
    id: "perfect-series",
    name: "Perfect Series",
    description: "Prove it was not luck — score three perfect quizzes",
    narrative: "Three perfect scores. At this point, it's a pattern, not an accident. You're not just reading — you're mastering.",
    category: "mastery",
    tier: "gold",
    icon: "⭐",
    fpValue: 50,
    isSecret: false,
    criteria: { type: "count", description: "3 perfect quiz scores", target: 3 },
    relatedBadgeIds: ["perfect-pass"],
    evaluate: (s) => ({ current: Math.min(s.perfectQuizCount, 3), target: 3 }),
  },
  {
    id: "mastery-baseline",
    name: "Mastery Baseline",
    description: "Hold a quiz average above eighty across ten quizzes",
    narrative: "An average above eighty across ten quizzes. Consistent comprehension is harder than occasional brilliance. This badge proves you have both.",
    category: "mastery",
    tier: "silver",
    icon: "📊",
    fpValue: 50,
    isSecret: false,
    criteria: { type: "compound", description: ">=80% avg over 10 quizzes", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({
      current: s.quizCount >= 10 && s.avgQuizScore >= 80 ? 1 : 0,
      target: 1,
    }),
  },
  {
    id: "answer-bank",
    name: "Answer Bank",
    description: "Answer one hundred quiz questions",
    narrative: "One hundred questions faced and answered. That's a hundred moments of testing yourself, a hundred chances to learn what you know and what you don't.",
    category: "mastery",
    tier: "unique",
    icon: "🏦",
    fpValue: 45,
    isSecret: false,
    criteria: { type: "count", description: "100 total quiz answers", target: 100 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.totalQuizQuestionsAnswered, 100), target: 100 }),
  },
  {
    id: "the-examiner",
    name: "The Examiner",
    description: "Pass twenty-five quizzes across any books",
    narrative: "Twenty-five quizzes passed across your reading journey. You've been tested again and again, and each time, you've proven your understanding.",
    category: "mastery",
    tier: "gold",
    icon: "🎓",
    fpValue: 65,
    isSecret: false,
    criteria: { type: "count", description: "25 quizzes passed", target: 25 },
    relatedBadgeIds: ["first-proof"],
    tieredProgression: { currentTier: "bronze", nextTier: "gold", nextTierTarget: 25, nextTierBadgeId: undefined },
    evaluate: (s) => ({ current: Math.min(s.quizzesPassed, 25), target: 25 }),
  },
  {
    id: "deep-focus",
    name: "Deep Focus",
    description: "Complete five chapters with focus mode turned on",
    narrative: "Five chapters completed with focus mode on — no distractions, no multitasking. This is what it looks like when you give a book your full attention.",
    category: "mastery",
    tier: "silver",
    icon: "🎯",
    fpValue: 40,
    isSecret: false,
    criteria: { type: "count", description: "5 chapters in focus mode", target: 5 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.chaptersCompletedWithFocusMode, 5), target: 5 }),
  },

  // ── Books & Completion ────────────────────────────────────────────────────
  {
    id: "cover-to-cover",
    name: "Cover to Cover",
    description: "Finish your first book — from first page to last",
    narrative: "You finished an entire book. From the first chapter to the last, you stayed with it. In a world of half-finished things, completion is rare and valuable.",
    category: "books",
    tier: "bronze",
    icon: "📖",
    fpValue: 50,
    isSecret: false,
    criteria: { type: "count", description: "Complete 1 book", target: 1 },
    relatedBadgeIds: ["shelf-builder"],
    evaluate: (s) => ({ current: Math.min(s.completedBooks, 1), target: 1 }),
  },
  {
    id: "shelf-builder",
    name: "Shelf Builder",
    description: "Finish three books and start building your personal library",
    narrative: "Three books finished. You're not just a reader anymore — you're building a personal library of completed knowledge. Each book is a world fully explored.",
    category: "books",
    tier: "silver",
    icon: "📚",
    fpValue: 65,
    isSecret: false,
    criteria: { type: "count", description: "Complete 3 books", target: 3 },
    relatedBadgeIds: ["cover-to-cover"],
    evaluate: (s) => ({ current: Math.min(s.completedBooks, 3), target: 3 }),
  },
  {
    id: "hard-finish",
    name: "Hard Finish",
    description: "Finish a challenging book — the ones worth struggling through",
    narrative: "You chose a challenging book and finished it. The struggle was the point — the ideas worth having are rarely the easiest to earn.",
    category: "books",
    tier: "gold",
    icon: "💪",
    fpValue: 75,
    isSecret: false,
    criteria: { type: "count", description: "Complete 1 book tagged as hard", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.challengingBooksCompleted, 1), target: 1 }),
  },
  {
    id: "mind-reader",
    name: "Mind Reader",
    description: "Finish a psychology category book",
    narrative: "A psychology book, completed. You now carry a map of the human mind that most people never bother to unfold.",
    category: "books",
    tier: "unique",
    icon: "🧠",
    fpValue: 50,
    isSecret: false,
    criteria: { type: "count", description: "Complete 1 psychology book", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.psychologyBooksCompleted, 1), target: 1 }),
  },
  {
    id: "strategy-closer",
    name: "Strategy Closer",
    description: "Finish a strategy category book",
    narrative: "A strategy book, finished. The frameworks and mental models you've absorbed are tools you'll use long after you close the app.",
    category: "books",
    tier: "unique",
    icon: "♟️",
    fpValue: 50,
    isSecret: false,
    criteria: { type: "count", description: "Complete 1 strategy book", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.strategyBooksCompleted, 1), target: 1 }),
  },
  {
    id: "cross-book-mastery",
    name: "Cross Book Mastery",
    description: "Pass quizzes in three different books",
    narrative: "Quizzes passed across three different books. Your understanding isn't narrow — it spans multiple authors, multiple perspectives, multiple worlds of thought.",
    category: "books",
    tier: "unique",
    icon: "🏆",
    fpValue: 55,
    isSecret: false,
    criteria: { type: "count", description: "Pass quizzes in 3 distinct books", target: 3 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.distinctQuizBooks, 3), target: 3 }),
  },

  // ── Exploration & Discovery ───────────────────────────────────────────────
  {
    id: "explorer",
    name: "Explorer",
    description: "Start books across three categories",
    narrative: "Three categories explored. You refused to stay in one lane, and that curiosity is exactly what separates interesting minds from ordinary ones.",
    category: "exploration",
    tier: "bronze",
    icon: "🧭",
    fpValue: 25,
    isSecret: false,
    criteria: { type: "count", description: "Start books in 3 categories", target: 3 },
    relatedBadgeIds: [],
    tieredProgression: { currentTier: "bronze", nextTier: "silver", nextTierTarget: 7 },
    evaluate: (s) => ({ current: Math.min(s.exploredCategories, 3), target: 3 }),
  },
  {
    id: "challenge-accepted",
    name: "Challenge Accepted",
    description: "Start a book tagged as hard — courage before comfort",
    narrative: "You looked at a hard book and opened it anyway. Courage before comfort — that's the mindset of someone who's serious about growth.",
    category: "exploration",
    tier: "unique",
    icon: "⚡",
    fpValue: 20,
    isSecret: false,
    criteria: { type: "count", description: "Start 1 hard book", target: 1 },
    relatedBadgeIds: ["hard-finish"],
    evaluate: (s) => ({ current: Math.min(s.challengingBooksStarted, 1), target: 1 }),
  },
  {
    id: "applied-reader",
    name: "Applied Reader",
    description: "Complete ten chapters where examples were actively used",
    narrative: "Ten chapters where you didn't just read — you applied. You connected ideas to your own life, your own context. That's how knowledge becomes wisdom.",
    category: "exploration",
    tier: "unique",
    icon: "🔧",
    fpValue: 40,
    isSecret: false,
    criteria: { type: "count", description: "10 chapters with examples used", target: 10 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.examplesViewedChapters, 10), target: 10 }),
  },
  {
    id: "lens-master",
    name: "Lens Master",
    description: "Use work, personal, and school example lenses across chapters",
    narrative: "You've used every lens the app offers — work, personal, school. Seeing ideas through multiple perspectives is the mark of a truly flexible thinker.",
    category: "exploration",
    tier: "silver",
    icon: "🔮",
    fpValue: 30,
    isSecret: false,
    criteria: { type: "compound", description: "Use all 3 lens types", target: 3 },
    relatedBadgeIds: [],
    tieredProgression: { currentTier: "bronze", nextTier: "silver", nextTierTarget: 2 },
    evaluate: (s) => ({ current: s.viewedExampleContexts.length, target: 3 }),
  },
  {
    id: "path-builder",
    name: "Path Builder",
    description: "Build a five-book reading list",
    narrative: "Five books on your reading list. You're not wandering — you're building a deliberate path through the world of ideas.",
    category: "exploration",
    tier: "unique",
    icon: "📋",
    fpValue: 20,
    isSecret: false,
    criteria: { type: "count", description: "Add 5 books to reading list", target: 5 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.readingListCount, 5), target: 5 }),
  },
  {
    id: "return-loop",
    name: "Return Loop",
    description: "Come back after a long gap and restart your reading progress",
    narrative: "You were gone, and now you're back. The hardest step isn't the first one — it's the one you take after falling off. Welcome home.",
    category: "exploration",
    tier: "unique",
    icon: "🔁",
    fpValue: 20,
    isSecret: false,
    criteria: { type: "boolean", description: "Return after 14+ days of inactivity", target: 1 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.returnedAfterLongGap, 1), target: 1 }),
  },

  // ── Notes & Reflection ────────────────────────────────────────────────────
  {
    id: "first-ink",
    name: "First Ink",
    description: "Save your first note — the first mark you leave on a book",
    narrative: "Your first note. The first mark you left on a book. This is where reading becomes a conversation between you and the author.",
    category: "notes",
    tier: "bronze",
    icon: "✍️",
    fpValue: 10,
    isSecret: false,
    criteria: { type: "count", description: "Save 1 note", target: 1 },
    relatedBadgeIds: ["deep-thought", "the-annotator"],
    evaluate: (s) => ({ current: Math.min(s.notesCount, 1), target: 1 }),
  },
  {
    id: "deep-thought",
    name: "Deep Thought",
    description: "Write five substantial notes — real thinking, not just highlights",
    narrative: "Five substantial notes — not quick highlights, but real thinking committed to words. This is the kind of reflection that transforms reading into understanding.",
    category: "notes",
    tier: "silver",
    icon: "💭",
    fpValue: 30,
    isSecret: false,
    criteria: { type: "count", description: "5 notes over 100 characters each", target: 5 },
    relatedBadgeIds: ["first-ink"],
    evaluate: (s) => ({ current: Math.min(s.notesCount, 5), target: 5 }),
  },
  {
    id: "cross-book-notes",
    name: "Cross Book Notes",
    description: "Save notes across three different books",
    narrative: "Notes across three different books. You're not just annotating — you're building a personal knowledge base that spans multiple domains.",
    category: "notes",
    tier: "unique",
    icon: "📝",
    fpValue: 45,
    isSecret: false,
    criteria: { type: "count", description: "Notes in 3 distinct books", target: 3 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.noteBooksCount, 3), target: 3 }),
  },
  {
    id: "the-annotator",
    name: "The Annotator",
    description: "Save notes across ten chapters",
    narrative: "Notes across ten chapters. You've developed the habit of thinking in writing, and that habit will compound into something remarkable over time.",
    category: "notes",
    tier: "silver",
    icon: "📑",
    fpValue: 40,
    isSecret: false,
    criteria: { type: "count", description: "Notes in 10 distinct chapters", target: 10 },
    relatedBadgeIds: ["first-ink"],
    evaluate: (s) => ({ current: Math.min(s.completedChaptersWithNotes, 10), target: 10 }),
  },
  {
    id: "reflection-closer",
    name: "Reflection Closer",
    description: "Finish five chapters that include written reflection",
    narrative: "Five chapters finished with written reflection. You didn't just consume these chapters — you digested them, turned them over, and made them yours.",
    category: "notes",
    tier: "unique",
    icon: "🪞",
    fpValue: 35,
    isSecret: false,
    criteria: { type: "count", description: "5 chapters completed with reflection notes", target: 5 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.completedChaptersWithReflection, 5), target: 5 }),
  },

  // ── Secret Badges ─────────────────────────────────────────────────────────
  {
    id: "night-owl",
    name: "Night Owl",
    description: "For the readers who burn the midnight oil",
    narrative: "The midnight hours, when the world is quiet and the words feel closer. You read when most people sleep, and there's something beautiful about that dedication.",
    category: "secret",
    tier: "secret",
    icon: "🦉",
    fpValue: 30,
    isSecret: true,
    criteria: { type: "boolean", description: "Read any chapter after midnight", target: 1 },
    relatedBadgeIds: [],
    evaluate: () => ({ current: 0, target: 1 }),
  },
  {
    id: "marathon-reader",
    name: "Marathon Reader",
    description: "When you could not put the book down",
    narrative: "Two hours without stopping. You fell into a book so deeply that time itself dissolved. That kind of absorption is rare — and it means the book chose you as much as you chose it.",
    category: "secret",
    tier: "secret",
    icon: "📖",
    fpValue: 35,
    isSecret: true,
    criteria: { type: "boolean", description: "Read for 2+ continuous hours", target: 1 },
    relatedBadgeIds: [],
    evaluate: () => ({ current: 0, target: 1 }),
  },
  {
    id: "polymath",
    name: "Polymath",
    description: "A mind that refuses to specialize",
    narrative: "Five categories in a single month. While others specialize, you wander — and that wandering is exactly how the most interesting minds are built.",
    category: "secret",
    tier: "secret",
    icon: "🎭",
    fpValue: 40,
    isSecret: true,
    criteria: { type: "count", description: "Read in 5+ categories within a month", target: 5 },
    relatedBadgeIds: [],
    evaluate: (s) => ({ current: Math.min(s.exploredCategories, 5), target: 5 }),
  },
  {
    id: "speed-scholar",
    name: "Speed Scholar",
    description: "Swift comprehension — summary to quiz in record time",
    narrative: "Summary to quiz in under ten minutes. Swift comprehension — you absorbed, processed, and proved understanding at remarkable speed.",
    category: "secret",
    tier: "secret",
    icon: "⚡",
    fpValue: 30,
    isSecret: true,
    criteria: { type: "boolean", description: "Complete chapter loop in under 10 minutes", target: 1 },
    relatedBadgeIds: [],
    evaluate: () => ({ current: 0, target: 1 }),
  },
];

export const FILTER_OPTIONS: { value: string; label: string }[] = [
  { value: "all", label: "All" },
  { value: "earned", label: "Earned" },
  { value: "locked", label: "Locked" },
  { value: "consistency", label: "Consistency" },
  { value: "mastery", label: "Mastery" },
  { value: "books", label: "Books" },
  { value: "exploration", label: "Exploration" },
  { value: "notes", label: "Notes" },
];
