import type { SettingSearchItem } from "../types/settings";

export const SETTINGS_SEARCH_INDEX: SettingSearchItem[] = [
  // Section 1: Reading Experience
  {
    id: "reading-profile",
    section: "reading",
    label: "Reading profiles",
    description: "Quick Learner, Balanced Reader, Deep Diver",
    keywords: ["profile", "preset", "bundle", "mode"],
  },
  {
    id: "font-family",
    section: "reading",
    label: "Font family",
    description: "Choose the typeface that feels most comfortable",
    keywords: ["font", "typeface", "typography", "text", "serif", "sans", "dyslexic", "opendyslexic"],
  },
  {
    id: "font-size",
    section: "reading",
    label: "Font size",
    description: "Adjust the reading text size in chapters",
    keywords: ["font", "size", "text", "bigger", "smaller", "zoom"],
  },
  {
    id: "line-spacing",
    section: "reading",
    label: "Line spacing",
    description: "Breathing room between lines of text",
    keywords: ["line", "spacing", "height", "leading", "gap"],
  },
  {
    id: "letter-spacing",
    section: "reading",
    label: "Letter spacing",
    description: "Space between individual characters",
    keywords: ["letter", "spacing", "tracking", "character"],
  },
  {
    id: "focus-mode",
    section: "reading",
    label: "Focus mode",
    description: "Sidebar and header fade away while reading",
    keywords: ["focus", "distraction", "zen", "clean", "minimal"],
  },
  {
    id: "progress-bar",
    section: "reading",
    label: "Progress bar",
    description: "A thin bar showing how far you've come",
    keywords: ["progress", "bar", "completion", "percentage"],
  },
  {
    id: "resume-position",
    section: "reading",
    label: "Pick up where you left off",
    description: "Automatically scroll to your last reading position",
    keywords: ["resume", "position", "scroll", "bookmark", "remember"],
  },
  {
    id: "reading-time",
    section: "reading",
    label: "Show reading time",
    description: "Display estimated time to finish each book and chapter",
    keywords: ["time", "estimate", "duration", "minutes", "reading"],
  },
  {
    id: "text-to-speech",
    section: "reading",
    label: "Text-to-speech",
    description: "Listen to chapters read aloud",
    keywords: ["tts", "speech", "audio", "listen", "voice", "narration", "read aloud"],
  },

  // Section 2: Goals & Motivation
  {
    id: "daily-goal",
    section: "goals",
    label: "Daily reading goal",
    description: "How much time you want to invest each day",
    keywords: ["daily", "goal", "minutes", "time", "habit"],
  },
  {
    id: "weekly-chapter-goal",
    section: "goals",
    label: "Weekly chapter goal",
    description: "Chapters to complete each week",
    keywords: ["weekly", "chapter", "goal", "target"],
  },
  {
    id: "question-flow",
    section: "goals",
    label: "Question flow",
    description: "See questions one at a time or all together",
    keywords: ["question", "flow", "presentation", "one-by-one", "all"],
  },
  {
    id: "shuffle-questions",
    section: "goals",
    label: "Shuffle questions",
    description: "Randomize the order each time you retake a quiz",
    keywords: ["shuffle", "random", "order", "quiz"],
  },
  {
    id: "retry-incorrect",
    section: "goals",
    label: "Retry incorrect only",
    description: "Focus only on the ones you got wrong",
    keywords: ["retry", "incorrect", "wrong", "repeat", "focus"],
  },
  {
    id: "streak-mode",
    section: "goals",
    label: "Streak mode",
    description: "Daily reading streak tracking",
    keywords: ["streak", "daily", "habit", "consistency", "flexible"],
  },
  {
    id: "motivation-style",
    section: "goals",
    label: "Motivation style",
    description: "How ChapterFlow encourages you",
    keywords: ["motivation", "encouragement", "coach", "rival", "nudge"],
  },
  {
    id: "content-tone",
    section: "reading",
    label: "Content tone",
    description: "How chapter summaries, scenarios, and quiz feedback are written",
    keywords: ["tone", "gentle", "direct", "competitive", "voice", "writing", "style", "content"],
  },
  {
    id: "spaced-repetition",
    section: "goals",
    label: "Review retention target",
    description: "How well you want to remember what you've read",
    keywords: ["spaced", "repetition", "review", "retention", "memory", "recall"],
  },

  // Section 3: Appearance
  {
    id: "theme",
    section: "appearance",
    label: "Theme",
    description: "Choose your preferred color scheme",
    keywords: ["theme", "dark", "light", "mode", "color", "scheme", "system"],
  },
  {
    id: "night-mode-schedule",
    section: "appearance",
    label: "Night mode schedule",
    description: "Automatically switch to dark mode during evening",
    keywords: ["night", "schedule", "dark", "evening", "auto", "time"],
  },
  {
    id: "reduced-motion",
    section: "appearance",
    label: "Reduced motion",
    description: "Minimize animations and transitions",
    keywords: ["motion", "animation", "transition", "reduce", "accessibility"],
  },

  // Section 4: Accessibility
  {
    id: "high-contrast",
    section: "accessibility",
    label: "High contrast",
    description: "Sharper colors and stronger borders",
    keywords: ["contrast", "high", "visibility", "readability", "colors"],
  },
  {
    id: "color-blind",
    section: "accessibility",
    label: "Color vision adjustment",
    description: "Adjust colors for different types of color vision",
    keywords: ["color", "blind", "vision", "protanopia", "deuteranopia", "tritanopia"],
  },
  {
    id: "keyboard-nav",
    section: "accessibility",
    label: "Keyboard navigation",
    description: "Tab to move, Enter to select, Escape to close",
    keywords: ["keyboard", "navigation", "tab", "screen reader", "a11y"],
  },

  // Section 5: Notifications
  {
    id: "reading-reminders",
    section: "notifications",
    label: "Reading reminders",
    description: "A friendly nudge at your chosen time",
    keywords: ["reminder", "notification", "nudge", "alert", "daily"],
  },
  {
    id: "reminder-time",
    section: "notifications",
    label: "Reminder time",
    description: "When to receive your daily reading nudge",
    keywords: ["time", "when", "schedule", "reminder"],
  },
  {
    id: "streak-alerts",
    section: "notifications",
    label: "Streak alerts",
    description: "Heads-up when your reading streak is about to expire",
    keywords: ["streak", "alert", "expire", "warning"],
  },
  {
    id: "break-reminders",
    section: "notifications",
    label: "Break reminders",
    description: "Reminder to rest your eyes during long sessions",
    keywords: ["break", "rest", "eyes", "health", "pause"],
  },
  {
    id: "weekly-summary",
    section: "notifications",
    label: "Weekly summary email",
    description: "A brief digest of your reading progress every Monday",
    keywords: ["weekly", "summary", "email", "digest", "progress"],
  },

  // Section 6: Account & Subscription
  {
    id: "subscription",
    section: "account",
    label: "Subscription status",
    description: "Your current plan and billing",
    keywords: ["subscription", "plan", "billing", "pro", "free", "upgrade", "price"],
  },
  {
    id: "analytics",
    section: "account",
    label: "Share usage analytics",
    description: "Help improve ChapterFlow with anonymous data",
    keywords: ["analytics", "data", "tracking", "privacy", "anonymous"],
  },
  {
    id: "recommendations",
    section: "account",
    label: "Personalized recommendations",
    description: "Use reading history to suggest books",
    keywords: ["recommendations", "suggest", "personalized", "books"],
  },
  {
    id: "reading-history",
    section: "account",
    label: "Save reading history",
    description: "Remember which chapters and books you've completed",
    keywords: ["history", "save", "remember", "completed"],
  },
  {
    id: "export-data",
    section: "account",
    label: "Export my data",
    description: "Download your reading history, highlights, notes",
    keywords: ["export", "download", "data", "csv", "json", "markdown", "backup"],
  },
  {
    id: "refresh-preferences",
    section: "account",
    label: "Refresh my preferences",
    description: "Re-run the personalization wizard",
    keywords: ["refresh", "reset", "onboarding", "wizard", "personalization"],
  },
  {
    id: "deactivate",
    section: "account",
    label: "Deactivate account",
    description: "Temporarily disable your account",
    keywords: ["deactivate", "disable", "suspend", "pause"],
  },
  {
    id: "delete-account",
    section: "account",
    label: "Delete account & all data",
    description: "Permanently erase your account",
    keywords: ["delete", "erase", "remove", "permanent", "destroy"],
  },
];
