#!/usr/bin/env tsx

/**
 * Walks book-packages/*.modern.json and writes a v21-style chapter index for
 * each at state/indexes/<bookId>.json. Skips books that already have a
 * <bookId>.v21.json package (already migrated) and skips books whose index
 * already exists (idempotent). Also emits a migration roster summarizing
 * status across all books.
 *
 * Used to bootstrap the v13 → v21 migration: each fresh operator session
 * picks a pending book from the roster and runs `generate-book <bookId>`
 * against the pre-built index.
 *
 *   npx tsx scripts/book/prompts/chapterflow-v21-authored/src/scratch/extract-all-chapter-indexes.ts
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../../../../../..");
const BOOK_PACKAGES = resolve(REPO_ROOT, "book-packages");
const STATE_INDEXES = resolve(__dirname, "../../state/indexes");

type RosterRow = {
  bookId: string;
  title: string;
  author: string;
  chapterCount: number;
  status: "v21-shipped" | "index-ready" | "index-written";
  notes?: string;
};

function pad(n: number): string {
  return String(n).padStart(2, "0");
}

function main() {
  const files = readdirSync(BOOK_PACKAGES).filter((f) => f.endsWith(".modern.json"));
  const roster: RosterRow[] = [];
  let written = 0;
  let skippedShipped = 0;
  let skippedExists = 0;

  for (const file of files) {
    const path = resolve(BOOK_PACKAGES, file);
    const pkg = JSON.parse(readFileSync(path, "utf8"));
    const bookId: string | undefined = pkg?.book?.bookId;
    if (!bookId) {
      console.warn(`Skipping ${file}: missing book.bookId`);
      continue;
    }

    const v21Path = resolve(BOOK_PACKAGES, `${bookId}.v21.json`);
    if (existsSync(v21Path)) {
      roster.push({
        bookId,
        title: pkg.book?.title ?? bookId,
        author: pkg.book?.author ?? "",
        chapterCount: Array.isArray(pkg.chapters) ? pkg.chapters.length : 0,
        status: "v21-shipped",
        notes: "v21 package already exists in book-packages/",
      });
      skippedShipped += 1;
      continue;
    }

    const indexPath = resolve(STATE_INDEXES, `${bookId}.json`);
    if (existsSync(indexPath)) {
      const existing = JSON.parse(readFileSync(indexPath, "utf8"));
      roster.push({
        bookId,
        title: pkg.book?.title ?? bookId,
        author: pkg.book?.author ?? "",
        chapterCount: Array.isArray(existing) ? existing.length : 0,
        status: "index-ready",
        notes: "chapter index already extracted; ready to run generate-book",
      });
      skippedExists += 1;
      continue;
    }

    const chapters = Array.isArray(pkg.chapters) ? pkg.chapters : [];
    const index = chapters.map((ch: any, i: number) => ({
      chapterId: `${bookId}-ch${pad(typeof ch.number === "number" ? ch.number : i + 1)}`,
      chapterNumber: typeof ch.number === "number" ? ch.number : i + 1,
      chapterTitle: typeof ch.title === "string" ? ch.title : `Chapter ${i + 1}`,
    }));

    writeFileSync(indexPath, JSON.stringify(index, null, 2), "utf8");
    written += 1;
    roster.push({
      bookId,
      title: pkg.book?.title ?? bookId,
      author: pkg.book?.author ?? "",
      chapterCount: index.length,
      status: "index-written",
    });
  }

  // Write the roster as both JSON and Markdown for human-readable status.
  const rosterJsonPath = resolve(__dirname, "../../state/migration-roster.json");
  writeFileSync(rosterJsonPath, JSON.stringify(roster, null, 2), "utf8");

  const rosterMdPath = resolve(__dirname, "../../MIGRATION-ROSTER.md");
  const sorted = [...roster].sort((a, b) => {
    const orderOf = (r: RosterRow) => (r.status === "v21-shipped" ? 0 : r.status === "index-ready" ? 1 : 2);
    if (orderOf(a) !== orderOf(b)) return orderOf(a) - orderOf(b);
    return a.title.localeCompare(b.title);
  });
  const lines: string[] = [];
  lines.push(`# v13 → v21 Migration Roster`);
  lines.push("");
  lines.push(
    `Auto-generated by extract-all-chapter-indexes.ts. ${roster.length} books total — ` +
      `${roster.filter((r) => r.status === "v21-shipped").length} shipped, ` +
      `${roster.filter((r) => r.status !== "v21-shipped").length} pending.`,
  );
  lines.push("");
  lines.push(`Each pending book has a chapter index pre-built at ` +
    `\`state/indexes/<bookId>.json\`. To migrate one: open a fresh Claude or ` +
    `GPT/Codex session, paste \`MIGRATION-OPERATOR-PROMPT.md\`, and pick the ` +
    `next pending bookId from the table.`);
  lines.push("");
  lines.push(`| Status | Book | Author | Chapters | bookId |`);
  lines.push(`|--------|------|--------|----------|--------|`);
  for (const r of sorted) {
    const icon = r.status === "v21-shipped" ? "✓" : r.status === "index-ready" ? "○" : "○";
    const label =
      r.status === "v21-shipped" ? "shipped" : r.status === "index-ready" ? "ready" : "ready";
    lines.push(`| ${icon} ${label} | ${r.title} | ${r.author} | ${r.chapterCount} | \`${r.bookId}\` |`);
  }
  writeFileSync(rosterMdPath, lines.join("\n") + "\n", "utf8");

  console.log(`extract-all-chapter-indexes done.`);
  console.log(`  Books scanned:      ${files.length}`);
  console.log(`  Already shipped:    ${skippedShipped}`);
  console.log(`  Index already had:  ${skippedExists}`);
  console.log(`  Indexes written:    ${written}`);
  console.log(`  Roster:             ${rosterMdPath}`);
}

main();
