// TEST FIXTURES — a throwaway EC (P-256) certificate chain that mimics Apple's
// [leaf, intermediate, root] JWS x5c chain, plus an intermediate-signed leaf
// whose validity window is in the past ("expired"). Used ONLY by
// apple-jws-verify-core.test.ts, which signs JWSs with the leaf key and verifies
// them against the test root. These keys are NOT secret (generated at authoring
// time with `openssl`, never used in production).

export const ROOT_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIB+DCCAZ2gAwIBAgIURbj9Wzp96YWb/URgDAC6eM34iFMwCgYIKoZIzj0EAwIw
UTEnMCUGA1UEAwweQ2hhcHRlckZsb3cgVGVzdCBBcHBsZSBSb290IENBMRkwFwYD
VQQKDBBDaGFwdGVyRmxvdyBUZXN0MQswCQYDVQQGEwJVUzAeFw0yNjA3MDMwNTEx
MzVaFw0zNjA2MzAwNTExMzVaMFExJzAlBgNVBAMMHkNoYXB0ZXJGbG93IFRlc3Qg
QXBwbGUgUm9vdCBDQTEZMBcGA1UECgwQQ2hhcHRlckZsb3cgVGVzdDELMAkGA1UE
BhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQaAqdhNpu16xcSZD0yaMnG
dyQSnPreZSgid685RMKV2RMYyVeoeT60o2JLA8U+ieTWS7KYPXaO5rpe91N+jDaV
o1MwUTAdBgNVHQ4EFgQUAG4ifL4Bk8ONGrdy2w2HNvf4rmowHwYDVR0jBBgwFoAU
AG4ifL4Bk8ONGrdy2w2HNvf4rmowDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQD
AgNJADBGAiEAiOIk9uX5Ct9A6nfpaaoPGLM+wqZ1xsqdPLuj9X/bRBACIQCBH0+C
ljq8gDeYBWMHTI5rzmKUCo/gptmgj/I1IuS/vQ==
-----END CERTIFICATE-----
`;

export const INTERMEDIATE_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIICADCCAaWgAwIBAgIUamn+n4YIanrs3bWqYNjOzLcCCWgwCgYIKoZIzj0EAwIw
UTEnMCUGA1UEAwweQ2hhcHRlckZsb3cgVGVzdCBBcHBsZSBSb290IENBMRkwFwYD
VQQKDBBDaGFwdGVyRmxvdyBUZXN0MQswCQYDVQQGEwJVUzAeFw0yNjA3MDMwNTEx
MzVaFw0zMTA3MDIwNTExMzVaMFkxLzAtBgNVBAMMJkNoYXB0ZXJGbG93IFRlc3Qg
QXBwbGUgSW50ZXJtZWRpYXRlIENBMRkwFwYDVQQKDBBDaGFwdGVyRmxvdyBUZXN0
MQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABE4x7z4WenAr
GCR8I/S7NObvs0h4h4iApIXxzDwzeAN2I0uT/LqqUMUyxGnFNBq7BCpAD8cnED/T
f/vor9r3DeKjUzBRMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFIstOPZoMmiW
sFiJr4BN5sucEirOMB8GA1UdIwQYMBaAFABuIny+AZPDjRq3ctsNhzb3+K5qMAoG
CCqGSM49BAMCA0kAMEYCIQDM2hhViyvZfXeVrGgC51hZBC3qqcTq0aL87OCG1ig4
8QIhAImusrHIbLLizPHae3l8VTYHfvK/04FWJ1T6XPflpHjn
-----END CERTIFICATE-----
`;

export const LEAF_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIB+TCCAZ+gAwIBAgIUcR5C/p0myeWGZi6vU0VovMaegVAwCgYIKoZIzj0EAwIw
WTEvMC0GA1UEAwwmQ2hhcHRlckZsb3cgVGVzdCBBcHBsZSBJbnRlcm1lZGlhdGUg
Q0ExGTAXBgNVBAoMEENoYXB0ZXJGbG93IFRlc3QxCzAJBgNVBAYTAlVTMB4XDTI2
MDcwMzA1MTEzNVoXDTI4MTAwNTA1MTEzNVowTjEkMCIGA1UEAwwbQ2hhcHRlckZs
b3cgVGVzdCBBcHBsZSBMZWFmMRkwFwYDVQQKDBBDaGFwdGVyRmxvdyBUZXN0MQsw
CQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOEyziBiz6ttfdGW
Uo7eOLIaaN+zRJ9kqtifGHjv6Lpa+3U7vlzz/5p342NzQbCrreZNFYyaR0g17Sov
RWuhH4mjUDBOMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFI/fvNczDT2QkWItzEf3
935RX0JcMB8GA1UdIwQYMBaAFIstOPZoMmiWsFiJr4BN5sucEirOMAoGCCqGSM49
BAMCA0gAMEUCIGp2UokEmm+VTfrZRZ63L2P1GQwwPbdsr2hARzy4mZ1fAiEA743n
082cdLS//62jwCatLH2j/Spg2esnkCtZx2OeIt0=
-----END CERTIFICATE-----
`;

// The leaf's PKCS#8 private key as bare base64 DER (no PEM armor) so the
// throwaway test key does not trip secret scanners. The test reconstructs a
// KeyObject via crypto.createPrivateKey({ format: "der", type: "pkcs8" }).
export const LEAF_PRIVATE_KEY_PKCS8_DER_B64 =
  "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkuf3pKfr4G/LhoU80TpcH9ODF///ZyQfBkVn3qr+nnehRANCAAThMs4gYs+rbX3RllKO3jiyGmjfs0SfZKrYnxh47+i6Wvt1O75c8/+ad+Njc0Gwq63mTRWMmkdINe0qL0VroR+J";

export const EXPIRED_LEAF_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIICATCCAaegAwIBAgIUcR5C/p0myeWGZi6vU0VovMaegVEwCgYIKoZIzj0EAwIw
WTEvMC0GA1UEAwwmQ2hhcHRlckZsb3cgVGVzdCBBcHBsZSBJbnRlcm1lZGlhdGUg
Q0ExGTAXBgNVBAoMEENoYXB0ZXJGbG93IFRlc3QxCzAJBgNVBAYTAlVTMB4XDTIw
MDEwMTAwMDAwMFoXDTIwMDIwMTAwMDAwMFowVjEsMCoGA1UEAwwjQ2hhcHRlckZs
b3cgVGVzdCBBcHBsZSBFeHBpcmVkIExlYWYxGTAXBgNVBAoMEENoYXB0ZXJGbG93
IFRlc3QxCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENLtx
KsvhWAdNKF1LXCr8oELSjolzLG07OfohSq5wHfauI9LmsFHIqBlaZVYVCza/k36a
C7z5259O+Q2g5IhCxKNQME4wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUvOUNJvwQ
LFVSqyNxgcu9dOcbU8EwHwYDVR0jBBgwFoAUiy049mgyaJawWImvgE3my5wSKs4w
CgYIKoZIzj0EAwIDSAAwRQIhALxKxdCWJaYmKLiEhcdH09ILhrwp/RyL2Ejf3BaH
Iui/AiA3fPLs9gcR1My0+Y1CZfNuM+qQR9KyHHbi3C++2rHnZg==
-----END CERTIFICATE-----
`;
