/**
 * Phase-0 frozen integration contracts — registry + freeze verification
 * (IMP-00 items 12–13; master plan §8.2, §12 contract-change rule).
 *
 * `contract-manifest.json` (sibling file, generated by `generateManifest.ts`,
 * committed) pins { name, version, hash } for every contract. The
 * contracts-freeze test recomputes hashes from the live descriptors and fails
 * on ANY divergence, so a parallel work package cannot silently redefine a
 * shared interface: it must bump the version, regenerate the manifest, and
 * surface the diff for integration review.
 */

import { readFileSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

import { ContractDescriptor, contractHash } from "./contractUtil.js";
import { EXECUTION_PROFILE_CONTRACT } from "./executionProfile.js";
import { EFFECTIVE_CONTEXT_CONTRACT } from "./effectiveContext.js";
import { CANDIDATE_TRANSACTION_CONTRACT } from "./candidateTransaction.js";
import { SOURCE_USE_PLAN_CONTRACT } from "./sourceUsePlan.js";
import { REPAIR_CONTRACT } from "./repairContracts.js";
import { REVIEW_CONTRACT } from "./reviewContracts.js";
import { ROUTE_CONTRACT } from "./routeContracts.js";
import { ATTEMPT_EVIDENCE_CONTRACT } from "./attemptEvidence.js";
import { WORKER_REPORT_CONTRACT } from "./workerReport.js";
// IMP-20 — five additive split-lane reviewer / recovery contracts (Wave-C
// registration; manifest 9 → 14). Descriptor files authored in Wave A; no
// existing descriptor changes, so no existing contractHash moves.
import { READER_EXPERIENCE_REVIEW_CONTRACT } from "./readerExperienceReview.js";
import { SOURCE_INTEGRITY_REVIEW_CONTRACT } from "./sourceIntegrityReview.js";
import { QUIZ_INTEGRITY_RESULT_CONTRACT } from "./quizIntegrityReview.js";
import { AGGREGATED_CHAPTER_REVIEW_CONTRACT } from "./aggregateChapterReview.js";
import { JUDGE_CAPABILITY_QUALIFICATION_CONTRACT } from "./judgeCapabilityQualification.js";
import { REVIEW_EVIDENCE_ENVELOPE_CONTRACT } from "./reviewEvidenceEnvelope.js";
import { REVIEW_MODEL_OUTPUT_V2_CONTRACT } from "./reviewModelOutputV2.js";
// WP-102 — additive emission↔web-adapter parity contract (V25 S-Tier §8 Lane 1;
// manifest 16 → 17). Freezes the terminal v21 emission's consumer surface; no
// existing descriptor changes, so no existing contractHash moves.
import { EMISSION_PACKAGE_CONTRACT } from "./emissionPackage.js";

export const ALL_CONTRACTS: readonly ContractDescriptor[] = [
  EXECUTION_PROFILE_CONTRACT,
  EFFECTIVE_CONTEXT_CONTRACT,
  CANDIDATE_TRANSACTION_CONTRACT,
  SOURCE_USE_PLAN_CONTRACT,
  REPAIR_CONTRACT,
  REVIEW_CONTRACT,
  ROUTE_CONTRACT,
  ATTEMPT_EVIDENCE_CONTRACT,
  WORKER_REPORT_CONTRACT,
  READER_EXPERIENCE_REVIEW_CONTRACT,
  SOURCE_INTEGRITY_REVIEW_CONTRACT,
  QUIZ_INTEGRITY_RESULT_CONTRACT,
  AGGREGATED_CHAPTER_REVIEW_CONTRACT,
  JUDGE_CAPABILITY_QUALIFICATION_CONTRACT,
  REVIEW_EVIDENCE_ENVELOPE_CONTRACT,
  REVIEW_MODEL_OUTPUT_V2_CONTRACT,
  EMISSION_PACKAGE_CONTRACT,
];

export type ContractManifest = {
  schema: "contract-manifest-v1";
  frozenAtIso: string;
  contracts: Array<{ name: string; version: number; ownerPrompt: string; hash: string }>;
};

export function computeContractManifest(frozenAtIso: string): ContractManifest {
  return {
    schema: "contract-manifest-v1",
    frozenAtIso,
    contracts: ALL_CONTRACTS.map((c) => ({
      name: c.name,
      version: c.version,
      ownerPrompt: c.ownerPrompt,
      hash: contractHash(c),
    })).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)), // byte-wise: locale-independent
  };
}

const __dirname = dirname(fileURLToPath(import.meta.url));

export const CONTRACT_MANIFEST_PATH = resolve(__dirname, "contract-manifest.json");

export function loadFrozenManifest(path = CONTRACT_MANIFEST_PATH): ContractManifest {
  return JSON.parse(readFileSync(path, "utf8")) as ContractManifest;
}

/** Compare live descriptors against the frozen manifest. Returns human-readable
 *  divergences; [] = frozen state holds. Consumed by the freeze test AND by any
 *  package that must "verify the Phase 0 contract manifest before editing". */
export function contractFreezeDivergences(manifest = loadFrozenManifest()): string[] {
  const problems: string[] = [];
  const live = new Map(ALL_CONTRACTS.map((c) => [c.name, c]));
  const frozen = new Map(manifest.contracts.map((c) => [c.name, c]));
  for (const [name, c] of live) {
    const f = frozen.get(name);
    if (!f) { problems.push(`contract "${name}" is live but missing from the frozen manifest`); continue; }
    if (f.version !== c.version) problems.push(`contract "${name}" version drift: frozen v${f.version} vs live v${c.version}`);
    const h = contractHash(c);
    if (f.hash !== h) problems.push(`contract "${name}" hash drift: frozen ${f.hash.slice(0, 12)}… vs live ${h.slice(0, 12)}… (bump version + regenerate manifest + integration review)`);
  }
  for (const name of frozen.keys()) {
    if (!live.has(name)) problems.push(`contract "${name}" is frozen but no longer defined`);
  }
  return problems;
}

export * from "./contractUtil.js";
export * from "./executionProfile.js";
export * from "./effectiveContext.js";
export * from "./candidateTransaction.js";
export * from "./sourceUsePlan.js";
export * from "./repairContracts.js";
export * from "./reviewContracts.js";
export * from "./routeContracts.js";
export * from "./attemptEvidence.js";
export * from "./workerReport.js";
export * from "./readerExperienceReview.js";
export * from "./sourceIntegrityReview.js";
export * from "./quizIntegrityReview.js";
export * from "./aggregateChapterReview.js";
export * from "./judgeCapabilityQualification.js";
export * from "./reviewEvidenceEnvelope.js";
export * from "./reviewModelOutputV2.js";
export * from "./emissionPackage.js";
